[project]
name = "pll-portrait"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "antonponmath", email = "48967349+antonponmath@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
pll-portrait = "pll_portrait:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
